retail_banking_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dwh_postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 4